import = [
"~/.config/alacritty/themes/everforest_dark.toml"
]

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13
offset = { x = 1, y = 2 }

[env]
TERM = "xterm-256color"

[window]
padding = {x = 5, y = 5}
decorations = "Buttonless"
dynamic_padding = true
opacity = 1
option_as_alt = "Both"
startup_mode = "Maximized"

[selection]
save_to_clipboard = true
