gui:
  mouseEvents: true
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#ea999c'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#414559'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#ea999c'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'
  authorColors:
    '*': '#babbf1'
git:
  paging:
    colorArg: always
    pager: delta --paging=never --diff-so-fancy
  commit:
    signOff: true
  autoFetch: false
  autoRefresh: false
  parseEmoji: true
